
(function(){
  const D = {
    en: {
      "prepForm":"Prep Form",
      "wosAccount":"WOS Account",
      "requestVP":"Request VP",
      "requestMOE":"Request MOE",
      "constructionQuestion":"How many minutes of Construction Speedups are you planning to use?",
      "researchQuestion":"How many minutes of Research Speedups are you planning to use?",
      "trainingQuestion":"How many minutes of Training Speedups are you planning to use?",
      "minutesHint":"Please enter the total shown in minutes.",
      "fireCrystalsQuestion":"How many Fire Crystals are you planning to use?",
      "refinedQuestion":"How many Refined Fire Crystals are you planning to use?",
      "shardsQuestion":"How many Fire Crystal Shards are you planning to use?",
      "timeFrame":"Preferred UTC time frame",
      "specificTime":"Specific preferred time in UTC (optional)",
      "troopsQuestion":"What troops are you training/promoting?",
      "upgradingT12":"Upgrading to T12",
      "t12Info":"T12 Upgrade Information",
      "submitPrep":"Submit Prep Form",
      "prepClosed":"This Prep Form is currently closed.",
      "claimFirst":"Claim a WOS account before submitting the Prep Form.",
      "prepSuccess":"Prep Form submitted successfully.",
      "selectSomething":"Select at least one Prep Day request or T12 information.",
      "autoTranslate":"Auto-translate",
      "translationNote":"Automatic free-text translation needs a translation service. You can save translations manually below.",
      "editEvent":"Edit Event",
      "saveEventChanges":"Save Changes",
      "close":"Close",
      "castleAlliance":"Castle Alliance",
      "presidencyAlliance":"Presidency Alliance",
      "eventNotes":"Event Notes",
      "importantAnnouncement":"Important Announcement",
      "announcementHint":"Shown as a highlighted message on the NEXA home page.",
      "iveRead":"I’ve read this",
      "readConfirmed":"Read ✓",
      "announcementReads":"Announcement Reads",
      "optionalSchedulerNote":"Optional note to Scheduler",
      "mySubmissions":"My Submissions",
      "editSubmission":"Edit Submission",
      "submitted":"Submitted",
      "reviewed":"Reviewed",
      "partiallyScheduled":"Partially Scheduled",
      "scheduled":"Scheduled",
      "copyAlliance":"Copy Alliance Schedule",
      "copyDay":"Copy This Day",
      "copyFull":"Copy Full Schedule",
      "exportCsv":"Export CSV",
      "allAlliances":"All Alliances",
      "allDays":"All Days",
      "prepRequests":"Prep Requests",
      "scheduleTools":"Schedule Tools",
      admin:"Admin", adminAccess:"Admin access required.", discordProfile:"Discord Profile",
      signInDiscord:"Sign in with Discord", discordConnected:"Discord Connected",
      myAccounts:"My Accounts", claimAccount:"Claim your WOS account", open:"Open",
      accountSubtitle:"Link your in-game name, Player ID and alliance.",
      liveUpcoming:"Live & Upcoming Events", tapOpen:"Tap to open", live:"Live",
      viewEvent:"View Event", noLive:"No live SvS event", noLiveText:"Leadership has not published a live event yet.",
      endsIn:"Ends in", prepBattle:"Prep & Battle Phase", stateHub:"State 1518 • Events, accounts & coordination",
      motto:"One State. One Vision. One Victory.",
      wosAccounts:"WOS Accounts", yourTimeZone:"Your Time Zone", change:"Change",
      yourLanguage:"Language", languageAuto:"Auto (device)", saveLanguage:"Save Language",
      inGameName:"In-Game Name", playerId:"Player ID", alliance:"Alliance", selectAlliance:"Select alliance",
      notListed:"Not Listed", allianceTag:"Alliance Tag", addAccount:"Add Account", saveChanges:"Save Changes",
      cancel:"Cancel", edit:"Edit", delete:"Delete", noAccounts:"No WOS accounts claimed yet.",
      accountAdded:"Account added.", accountUpdated:"Account updated.", timezoneUpdated:"Time zone updated.",
      languageUpdated:"Language updated.", removeAccount:"Remove this WOS account from NEXA?",
      adminPanel:"ADMIN PANEL", controlCenter:"NEXA Control Center", events:"Events", alliances:"Alliances",
      permissions:"Permissions", svsEvents:"SvS Events",
      eventsHelp:"Create and manage the current SvS using official WOS Game Time (UTC).",
      opponentState:"Opponent State", prepMonday:"Prep Monday — Game Date (UTC)", eventNotes:"Event Notes",
      timeline:"AUTO-GENERATED WOS TIMELINE", chooseMonday:"Choose Prep Monday to preview dates.",
      prepFormOpen:"Prep Form Open", battleFormOpen:"Battle Form Open",
      schedulePublished:"Schedule Published", liveEvent:"Live Event", saveEvent:"Save Event",
      noEvents:"No SvS events created yet.", deleteEvent:"Delete this SvS event?",
      allianceTags:"Alliance Tags", allianceHelp:"Add, rename, or deactivate official alliance tags.",
      saveTag:"Save Tag", active:"Active", inactive:"Inactive", deactivate:"Deactivate", activate:"Activate",
      permissionsHelp:"Search by IGN or Player ID and assign access. Owner is protected.",
      searchUser:"Search IGN or Player ID", search:"Search", role:"Role", player:"Player",
      scheduler:"Scheduler", owner:"Owner", noUsers:"No matching users found.",
      roleUpdated:"Role updated.", ownerProtected:"Owner account is protected.",
      construction:"Construction", research:"Research", training:"Training", battle:"Castle Battle & PvP",
      fillPrep:"Fill Out Prep Form", fillBattle:"Fill Out Battle Form", viewSchedule:"View Schedule",
      aboutEvent:"About this event", noNotes:"No additional notes have been published.",
      backEvents:"Back to events", backEvent:"Back to SvS event", ministrySchedule:"Ministry Schedule",
      officialUtc:"Official WOS time in UTC • your local time shown in AM/PM",
      appointments30:"Appointments every 30 minutes", yourTime:"Your time", openUnassigned:"Open / Not assigned",
      publishedAppointments:"Published appointments • State 1518", ended:"Ended",
      monday:"MON", tuesday:"TUE", thursday:"THU", saturday:"SAT"
    },
    es: {
      "prepForm":"Formulario de Prep",
      "wosAccount":"Cuenta WOS",
      "requestVP":"Solicitar VP",
      "requestMOE":"Solicitar MOE",
      "constructionQuestion":"¿Cuántos minutos de speedups de construcción piensas usar?",
      "researchQuestion":"¿Cuántos minutos de speedups de investigación piensas usar?",
      "trainingQuestion":"¿Cuántos minutos de speedups de entrenamiento piensas usar?",
      "minutesHint":"Escribe el total que te muestra el juego en minutos.",
      "fireCrystalsQuestion":"¿Cuántos Fire Crystals piensas usar?",
      "refinedQuestion":"¿Cuántos Refined Fire Crystals piensas usar?",
      "shardsQuestion":"¿Cuántos Fire Crystal Shards piensas usar?",
      "timeFrame":"Franja horaria preferida en UTC",
      "specificTime":"Hora específica preferida en UTC (opcional)",
      "troopsQuestion":"¿Qué tropas vas a entrenar o promover?",
      "upgradingT12":"Subiendo a T12",
      "t12Info":"Información de mejora a T12",
      "submitPrep":"Enviar Prep Form",
      "prepClosed":"Este Prep Form está cerrado actualmente.",
      "claimFirst":"Vincula una cuenta WOS antes de enviar el Prep Form.",
      "prepSuccess":"Prep Form enviado correctamente.",
      "selectSomething":"Selecciona al menos un día de Prep o información de T12.",
      "autoTranslate":"Auto-traducir",
      "translationNote":"La traducción automática de texto libre necesita un servicio de traducción. Puedes guardar traducciones manualmente abajo.",
      "editEvent":"Editar evento",
      "saveEventChanges":"Guardar cambios",
      "close":"Cerrar",
      "castleAlliance":"Alianza del Castillo",
      "presidencyAlliance":"Alianza de Presidencia",
      "eventNotes":"Notas del evento",
      "importantAnnouncement":"Anuncio importante",
      "announcementHint":"Se mostrará como un mensaje destacado en la página principal de NEXA.",
      "iveRead":"Ya lo leí",
      "readConfirmed":"Leído ✓",
      "announcementReads":"Lecturas del anuncio",
      "optionalSchedulerNote":"Nota opcional para Scheduler",
      "mySubmissions":"Mis solicitudes",
      "editSubmission":"Editar solicitud",
      "submitted":"Enviado",
      "reviewed":"Revisado",
      "partiallyScheduled":"Parcialmente programado",
      "scheduled":"Programado",
      "copyAlliance":"Copiar schedule de alianza",
      "copyDay":"Copiar este día",
      "copyFull":"Copiar schedule completo",
      "exportCsv":"Exportar CSV",
      "allAlliances":"Todas las alianzas",
      "allDays":"Todos los días",
      "prepRequests":"Solicitudes Prep",
      "scheduleTools":"Herramientas de schedule",
      admin:"Admin", adminAccess:"Se requiere acceso de administrador.", discordProfile:"Perfil de Discord",
      signInDiscord:"Iniciar sesión con Discord", discordConnected:"Discord conectado",
      myAccounts:"Mis cuentas", claimAccount:"Vincular cuenta de WOS", open:"Abrir",
      accountSubtitle:"Vincula tu nombre del juego, Player ID y alianza.",
      liveUpcoming:"Eventos en vivo y próximos", tapOpen:"Toca para abrir", live:"En vivo",
      viewEvent:"Ver evento", noLive:"No hay SvS en vivo", noLiveText:"El liderazgo aún no ha publicado un evento en vivo.",
      endsIn:"Termina en", prepBattle:"Fase de Prep y Batalla", stateHub:"State 1518 • Eventos, cuentas y coordinación",
      motto:"Un State. Una visión. Una victoria.",
      wosAccounts:"Cuentas WOS", yourTimeZone:"Tu zona horaria", change:"Cambiar",
      yourLanguage:"Idioma", languageAuto:"Automático (dispositivo)", saveLanguage:"Guardar idioma",
      inGameName:"Nombre en el juego", playerId:"Player ID", alliance:"Alianza", selectAlliance:"Seleccionar alianza",
      notListed:"No está en la lista", allianceTag:"Tag de alianza", addAccount:"Añadir cuenta", saveChanges:"Guardar cambios",
      cancel:"Cancelar", edit:"Editar", delete:"Eliminar", noAccounts:"Aún no has vinculado cuentas de WOS.",
      accountAdded:"Cuenta añadida.", accountUpdated:"Cuenta actualizada.", timezoneUpdated:"Zona horaria actualizada.",
      languageUpdated:"Idioma actualizado.", removeAccount:"¿Quitar esta cuenta de WOS de NEXA?",
      adminPanel:"PANEL ADMIN", controlCenter:"Centro de control NEXA", events:"Eventos", alliances:"Alianzas",
      permissions:"Permisos", svsEvents:"Eventos SvS",
      eventsHelp:"Crea y administra el SvS actual usando el horario oficial de WOS (UTC).",
      opponentState:"State rival", prepMonday:"Lunes de Prep — Fecha del juego (UTC)", eventNotes:"Notas del evento",
      timeline:"CRONOGRAMA WOS AUTOMÁTICO", chooseMonday:"Elige el lunes de Prep para ver las fechas.",
      prepFormOpen:"Prep Form abierto", battleFormOpen:"Battle Form abierto",
      schedulePublished:"Schedule publicado", liveEvent:"Evento en vivo", saveEvent:"Guardar evento",
      noEvents:"Aún no hay eventos SvS creados.", deleteEvent:"¿Eliminar este evento SvS?",
      allianceTags:"Tags de alianzas", allianceHelp:"Añade, cambia o desactiva tags oficiales.",
      saveTag:"Guardar tag", active:"Activo", inactive:"Inactivo", deactivate:"Desactivar", activate:"Activar",
      permissionsHelp:"Busca por IGN o Player ID y asigna acceso. Owner está protegido.",
      searchUser:"Buscar IGN o Player ID", search:"Buscar", role:"Rol", player:"Player",
      scheduler:"Scheduler", owner:"Owner", noUsers:"No se encontraron usuarios.",
      roleUpdated:"Rol actualizado.", ownerProtected:"La cuenta Owner está protegida.",
      construction:"Construcción", research:"Investigación", training:"Entrenamiento", battle:"Batalla de Castillo y PvP",
      fillPrep:"Llenar Prep Form", fillBattle:"Llenar Battle Form", viewSchedule:"Ver schedule",
      aboutEvent:"Sobre este evento", noNotes:"No se han publicado notas adicionales.",
      backEvents:"Volver a eventos", backEvent:"Volver al evento SvS", ministrySchedule:"Schedule de Ministerios",
      officialUtc:"Hora oficial de WOS en UTC • tu hora local aparece en AM/PM",
      appointments30:"Citas cada 30 minutos", yourTime:"Tu hora", openUnassigned:"Disponible / Sin asignar",
      publishedAppointments:"Citas publicadas • State 1518", ended:"Finalizado",
      monday:"LUN", tuesday:"MAR", thursday:"JUE", saturday:"SÁB"
    },
    tr: {
      "prepForm":"Prep Formu",
      "wosAccount":"WOS Hesabı",
      "requestVP":"VP İste",
      "requestMOE":"MOE İste",
      "constructionQuestion":"Kaç dakika Construction Speedup kullanmayı planlıyorsun?",
      "researchQuestion":"Kaç dakika Research Speedup kullanmayı planlıyorsun?",
      "trainingQuestion":"Kaç dakika Training Speedup kullanmayı planlıyorsun?",
      "minutesHint":"Oyunda dakika olarak gösterilen toplamı gir.",
      "fireCrystalsQuestion":"Kaç Fire Crystal kullanmayı planlıyorsun?",
      "refinedQuestion":"Kaç Refined Fire Crystal kullanmayı planlıyorsun?",
      "shardsQuestion":"Kaç Fire Crystal Shard kullanmayı planlıyorsun?",
      "timeFrame":"Tercih edilen UTC zaman aralığı",
      "specificTime":"Tercih edilen özel UTC saati (isteğe bağlı)",
      "troopsQuestion":"Hangi birlikleri eğitiyor/yükseltiyorsun?",
      "upgradingT12":"T12'ye yükseltiyorum",
      "t12Info":"T12 Yükseltme Bilgisi",
      "submitPrep":"Prep Formunu Gönder",
      "prepClosed":"Bu Prep Form şu anda kapalı.",
      "claimFirst":"Prep Form göndermeden önce bir WOS hesabı bağla.",
      "prepSuccess":"Prep Form başarıyla gönderildi.",
      "selectSomething":"En az bir Prep günü veya T12 bilgisi seç.",
      "autoTranslate":"Otomatik çevir",
      "translationNote":"Serbest metin otomatik çevirisi için çeviri servisi gerekir. Aşağıya çevirileri manuel kaydedebilirsin.",
      "editEvent":"Etkinliği Düzenle",
      "saveEventChanges":"Değişiklikleri Kaydet",
      "close":"Kapat",
      "castleAlliance":"Kale İttifakı",
      "presidencyAlliance":"Başkanlık İttifakı",
      "eventNotes":"Etkinlik Notları",
      "importantAnnouncement":"Önemli Duyuru",
      "announcementHint":"NEXA ana sayfasında dikkat çekici mesaj olarak gösterilir.",
      "iveRead":"Okudum",
      "readConfirmed":"Okundu ✓",
      "announcementReads":"Duyuru Okuyanlar",
      "optionalSchedulerNote":"Scheduler için isteğe bağlı not",
      "mySubmissions":"Başvurularım",
      "editSubmission":"Başvuruyu Düzenle",
      "submitted":"Gönderildi",
      "reviewed":"İncelendi",
      "partiallyScheduled":"Kısmen Planlandı",
      "scheduled":"Planlandı",
      "copyAlliance":"İttifak Schedule Kopyala",
      "copyDay":"Bu Günü Kopyala",
      "copyFull":"Tüm Schedule Kopyala",
      "exportCsv":"CSV Dışa Aktar",
      "allAlliances":"Tüm İttifaklar",
      "allDays":"Tüm Günler",
      "prepRequests":"Prep Başvuruları",
      "scheduleTools":"Schedule Araçları",
      admin:"Yönetici", adminAccess:"Yönetici erişimi gerekli.", discordProfile:"Discord Profili",
      signInDiscord:"Discord ile giriş yap", discordConnected:"Discord bağlı",
      myAccounts:"Hesaplarım", claimAccount:"WOS hesabını bağla", open:"Aç",
      accountSubtitle:"Oyun adını, Player ID'ni ve ittifakını bağla.",
      liveUpcoming:"Canlı ve Yaklaşan Etkinlikler", tapOpen:"Açmak için dokun", live:"Canlı",
      viewEvent:"Etkinliği Gör", noLive:"Canlı SvS yok", noLiveText:"Liderlik henüz canlı etkinlik yayınlamadı.",
      endsIn:"Bitişe", prepBattle:"Hazırlık ve Savaş Aşaması", stateHub:"State 1518 • Etkinlikler, hesaplar ve koordinasyon",
      motto:"Tek State. Tek Vizyon. Tek Zafer.",
      wosAccounts:"WOS Hesapları", yourTimeZone:"Saat Dilimin", change:"Değiştir",
      yourLanguage:"Dil", languageAuto:"Otomatik (cihaz)", saveLanguage:"Dili Kaydet",
      inGameName:"Oyun Adı", playerId:"Player ID", alliance:"İttifak", selectAlliance:"İttifak seç",
      notListed:"Listede Yok", allianceTag:"İttifak Tagı", addAccount:"Hesap Ekle", saveChanges:"Değişiklikleri Kaydet",
      cancel:"İptal", edit:"Düzenle", delete:"Sil", noAccounts:"Henüz WOS hesabı bağlanmadı.",
      accountAdded:"Hesap eklendi.", accountUpdated:"Hesap güncellendi.", timezoneUpdated:"Saat dilimi güncellendi.",
      languageUpdated:"Dil güncellendi.", removeAccount:"Bu WOS hesabı NEXA'dan kaldırılsın mı?",
      adminPanel:"YÖNETİCİ PANELİ", controlCenter:"NEXA Kontrol Merkezi", events:"Etkinlikler", alliances:"İttifaklar",
      permissions:"İzinler", svsEvents:"SvS Etkinlikleri",
      eventsHelp:"Mevcut SvS'yi resmi WOS Oyun Saati (UTC) ile oluştur ve yönet.",
      opponentState:"Rakip State", prepMonday:"Hazırlık Pazartesisi — Oyun Tarihi (UTC)", eventNotes:"Etkinlik Notları",
      timeline:"OTOMATİK WOS ZAMAN ÇİZELGESİ", chooseMonday:"Tarihleri görmek için Hazırlık Pazartesisini seç.",
      prepFormOpen:"Prep Form Açık", battleFormOpen:"Battle Form Açık",
      schedulePublished:"Schedule Yayında", liveEvent:"Canlı Etkinlik", saveEvent:"Etkinliği Kaydet",
      noEvents:"Henüz SvS etkinliği oluşturulmadı.", deleteEvent:"Bu SvS etkinliği silinsin mi?",
      allianceTags:"İttifak Tagları", allianceHelp:"Resmi tagları ekle, değiştir veya devre dışı bırak.",
      saveTag:"Tagı Kaydet", active:"Aktif", inactive:"Pasif", deactivate:"Devre Dışı", activate:"Aktifleştir",
      permissionsHelp:"IGN veya Player ID ile ara ve erişim ata. Owner korunur.",
      searchUser:"IGN veya Player ID ara", search:"Ara", role:"Rol", player:"Player",
      scheduler:"Scheduler", owner:"Owner", noUsers:"Eşleşen kullanıcı yok.",
      roleUpdated:"Rol güncellendi.", ownerProtected:"Owner hesabı korunmaktadır.",
      construction:"İnşaat", research:"Araştırma", training:"Eğitim", battle:"Kale Savaşı ve PvP",
      fillPrep:"Prep Formu Doldur", fillBattle:"Battle Formu Doldur", viewSchedule:"Schedule Gör",
      aboutEvent:"Etkinlik hakkında", noNotes:"Ek not yayınlanmadı.",
      backEvents:"Etkinliklere dön", backEvent:"SvS etkinliğine dön", ministrySchedule:"Bakanlık Schedule",
      officialUtc:"Resmi WOS saati UTC • yerel saatin AM/PM olarak gösterilir",
      appointments30:"Her 30 dakikada randevu", yourTime:"Senin saatin", openUnassigned:"Boş / Atanmadı",
      publishedAppointments:"Yayınlanan randevular • State 1518", ended:"Bitti",
      monday:"PZT", tuesday:"SAL", thursday:"PER", saturday:"CMT"
    },
    ko: {
      "prepForm":"Prep Form",
      "wosAccount":"WOS 계정",
      "requestVP":"VP 신청",
      "requestMOE":"MOE 신청",
      "constructionQuestion":"건설 Speedup을 몇 분 사용할 예정인가요?",
      "researchQuestion":"연구 Speedup을 몇 분 사용할 예정인가요?",
      "trainingQuestion":"훈련 Speedup을 몇 분 사용할 예정인가요?",
      "minutesHint":"게임에 표시되는 총 분을 입력하세요.",
      "fireCrystalsQuestion":"Fire Crystal을 몇 개 사용할 예정인가요?",
      "refinedQuestion":"Refined Fire Crystal을 몇 개 사용할 예정인가요?",
      "shardsQuestion":"Fire Crystal Shard를 몇 개 사용할 예정인가요?",
      "timeFrame":"선호 UTC 시간대",
      "specificTime":"선호하는 특정 UTC 시간 (선택)",
      "troopsQuestion":"어떤 병력을 훈련/승급하나요?",
      "upgradingT12":"T12 승급",
      "t12Info":"T12 승급 정보",
      "submitPrep":"Prep Form 제출",
      "prepClosed":"현재 Prep Form이 닫혀 있습니다.",
      "claimFirst":"Prep Form 제출 전에 WOS 계정을 연결하세요.",
      "prepSuccess":"Prep Form이 제출되었습니다.",
      "selectSomething":"최소 하나의 Prep 요청 또는 T12 정보를 선택하세요.",
      "autoTranslate":"자동 번역",
      "translationNote":"자유 텍스트 자동 번역에는 번역 서비스가 필요합니다. 아래에 수동 번역을 저장할 수 있습니다.",
      "editEvent":"이벤트 수정",
      "saveEventChanges":"변경 저장",
      "close":"닫기",
      "castleAlliance":"성 담당 연맹",
      "presidencyAlliance":"대통령 담당 연맹",
      "eventNotes":"이벤트 메모",
      "importantAnnouncement":"중요 공지",
      "announcementHint":"NEXA 홈에 강조된 메시지로 표시됩니다.",
      "iveRead":"확인했습니다",
      "readConfirmed":"확인 완료 ✓",
      "announcementReads":"공지 확인 현황",
      "optionalSchedulerNote":"Scheduler에게 남길 선택 메모",
      "mySubmissions":"내 신청",
      "editSubmission":"신청 수정",
      "submitted":"제출됨",
      "reviewed":"검토됨",
      "partiallyScheduled":"일부 배정됨",
      "scheduled":"배정됨",
      "copyAlliance":"연맹 Schedule 복사",
      "copyDay":"이 날짜 복사",
      "copyFull":"전체 Schedule 복사",
      "exportCsv":"CSV 내보내기",
      "allAlliances":"모든 연맹",
      "allDays":"모든 날짜",
      "prepRequests":"Prep 신청",
      "scheduleTools":"Schedule 도구",
      admin:"관리자", adminAccess:"관리자 권한이 필요합니다.", discordProfile:"Discord 프로필",
      signInDiscord:"Discord로 로그인", discordConnected:"Discord 연결됨",
      myAccounts:"내 계정", claimAccount:"WOS 계정 연결", open:"열기",
      accountSubtitle:"게임 이름, Player ID, 연맹을 연결하세요.",
      liveUpcoming:"진행 중 및 예정 이벤트", tapOpen:"눌러서 열기", live:"진행 중",
      viewEvent:"이벤트 보기", noLive:"진행 중인 SvS 없음", noLiveText:"아직 라이브 이벤트가 게시되지 않았습니다.",
      endsIn:"종료까지", prepBattle:"준비 및 전투 단계", stateHub:"State 1518 • 이벤트, 계정 및 조정",
      motto:"하나의 State. 하나의 비전. 하나의 승리.",
      wosAccounts:"WOS 계정", yourTimeZone:"내 시간대", change:"변경",
      yourLanguage:"언어", languageAuto:"자동 (기기)", saveLanguage:"언어 저장",
      inGameName:"게임 내 이름", playerId:"Player ID", alliance:"연맹", selectAlliance:"연맹 선택",
      notListed:"목록에 없음", allianceTag:"연맹 태그", addAccount:"계정 추가", saveChanges:"변경 저장",
      cancel:"취소", edit:"수정", delete:"삭제", noAccounts:"연결된 WOS 계정이 없습니다.",
      accountAdded:"계정이 추가되었습니다.", accountUpdated:"계정이 업데이트되었습니다.", timezoneUpdated:"시간대가 업데이트되었습니다.",
      languageUpdated:"언어가 업데이트되었습니다.", removeAccount:"이 WOS 계정을 NEXA에서 제거할까요?",
      adminPanel:"관리자 패널", controlCenter:"NEXA 컨트롤 센터", events:"이벤트", alliances:"연맹",
      permissions:"권한", svsEvents:"SvS 이벤트",
      eventsHelp:"공식 WOS 게임 시간(UTC)을 사용해 현재 SvS를 관리합니다.",
      opponentState:"상대 State", prepMonday:"준비 월요일 — 게임 날짜 (UTC)", eventNotes:"이벤트 메모",
      timeline:"자동 WOS 일정", chooseMonday:"준비 월요일을 선택하면 날짜를 미리 볼 수 있습니다.",
      prepFormOpen:"Prep Form 열림", battleFormOpen:"Battle Form 열림",
      schedulePublished:"Schedule 게시됨", liveEvent:"라이브 이벤트", saveEvent:"이벤트 저장",
      noEvents:"생성된 SvS 이벤트가 없습니다.", deleteEvent:"이 SvS 이벤트를 삭제할까요?",
      allianceTags:"연맹 태그", allianceHelp:"공식 태그를 추가, 변경 또는 비활성화합니다.",
      saveTag:"태그 저장", active:"활성", inactive:"비활성", deactivate:"비활성화", activate:"활성화",
      permissionsHelp:"IGN 또는 Player ID로 검색해 권한을 부여합니다. Owner는 보호됩니다.",
      searchUser:"IGN 또는 Player ID 검색", search:"검색", role:"역할", player:"Player",
      scheduler:"Scheduler", owner:"Owner", noUsers:"일치하는 사용자가 없습니다.",
      roleUpdated:"역할이 업데이트되었습니다.", ownerProtected:"Owner 계정은 보호됩니다.",
      construction:"건설", research:"연구", training:"훈련", battle:"성 전투 및 PvP",
      fillPrep:"Prep Form 작성", fillBattle:"Battle Form 작성", viewSchedule:"Schedule 보기",
      aboutEvent:"이 이벤트 정보", noNotes:"추가 메모가 게시되지 않았습니다.",
      backEvents:"이벤트로 돌아가기", backEvent:"SvS 이벤트로 돌아가기", ministrySchedule:"장관 Schedule",
      officialUtc:"공식 WOS 시간은 UTC • 현지 시간은 AM/PM으로 표시",
      appointments30:"30분 간격 예약", yourTime:"내 시간", openUnassigned:"비어 있음 / 미배정",
      publishedAppointments:"게시된 예약 • State 1518", ended:"종료",
      monday:"월", tuesday:"화", thursday:"목", saturday:"토"
    },
    ar: {
      "prepForm":"Prep Form",
      "wosAccount":"حساب WOS",
      "requestVP":"طلب VP",
      "requestMOE":"طلب MOE",
      "constructionQuestion":"كم دقيقة من Construction Speedups تخطط لاستخدامها؟",
      "researchQuestion":"كم دقيقة من Research Speedups تخطط لاستخدامها؟",
      "trainingQuestion":"كم دقيقة من Training Speedups تخطط لاستخدامها؟",
      "minutesHint":"أدخل الإجمالي الذي يظهر في اللعبة بالدقائق.",
      "fireCrystalsQuestion":"كم Fire Crystal تخطط لاستخدامه؟",
      "refinedQuestion":"كم Refined Fire Crystal تخطط لاستخدامه؟",
      "shardsQuestion":"كم Fire Crystal Shard تخطط لاستخدامه؟",
      "timeFrame":"الفترة المفضلة بتوقيت UTC",
      "specificTime":"وقت UTC محدد مفضل (اختياري)",
      "troopsQuestion":"ما القوات التي تدربها أو ترقيها؟",
      "upgradingT12":"الترقية إلى T12",
      "t12Info":"معلومات ترقية T12",
      "submitPrep":"إرسال Prep Form",
      "prepClosed":"Prep Form مغلق حاليًا.",
      "claimFirst":"اربط حساب WOS قبل إرسال Prep Form.",
      "prepSuccess":"تم إرسال Prep Form بنجاح.",
      "selectSomething":"اختر طلب Prep واحدًا على الأقل أو معلومات T12.",
      "autoTranslate":"ترجمة تلقائية",
      "translationNote":"الترجمة التلقائية للنص الحر تحتاج خدمة ترجمة. يمكنك حفظ الترجمات يدويًا أدناه.",
      "editEvent":"تعديل الحدث",
      "saveEventChanges":"حفظ التغييرات",
      "close":"إغلاق",
      "castleAlliance":"تحالف القلعة",
      "presidencyAlliance":"تحالف الرئاسة",
      "eventNotes":"ملاحظات الحدث",
      "importantAnnouncement":"إعلان مهم",
      "announcementHint":"يظهر كرسالة بارزة في الصفحة الرئيسية لـ NEXA.",
      "iveRead":"قرأت هذا",
      "readConfirmed":"تمت القراءة ✓",
      "announcementReads":"من قرأ الإعلان",
      "optionalSchedulerNote":"ملاحظة اختيارية للـ Scheduler",
      "mySubmissions":"طلباتي",
      "editSubmission":"تعديل الطلب",
      "submitted":"تم الإرسال",
      "reviewed":"تمت المراجعة",
      "partiallyScheduled":"تمت الجدولة جزئيًا",
      "scheduled":"تمت الجدولة",
      "copyAlliance":"نسخ Schedule التحالف",
      "copyDay":"نسخ هذا اليوم",
      "copyFull":"نسخ Schedule كامل",
      "exportCsv":"تصدير CSV",
      "allAlliances":"كل التحالفات",
      "allDays":"كل الأيام",
      "prepRequests":"طلبات Prep",
      "scheduleTools":"أدوات Schedule",
      admin:"الإدارة", adminAccess:"يلزم وصول المسؤول.", discordProfile:"ملف Discord",
      signInDiscord:"تسجيل الدخول عبر Discord", discordConnected:"Discord متصل",
      myAccounts:"حساباتي", claimAccount:"ربط حساب WOS", open:"فتح",
      accountSubtitle:"اربط اسمك داخل اللعبة وPlayer ID والتحالف.",
      liveUpcoming:"الأحداث المباشرة والقادمة", tapOpen:"اضغط للفتح", live:"مباشر",
      viewEvent:"عرض الحدث", noLive:"لا يوجد SvS مباشر", noLiveText:"لم تنشر القيادة حدثًا مباشرًا بعد.",
      endsIn:"ينتهي خلال", prepBattle:"مرحلة التحضير والمعركة", stateHub:"State 1518 • الأحداث والحسابات والتنسيق",
      motto:"State واحد. رؤية واحدة. نصر واحد.",
      wosAccounts:"حسابات WOS", yourTimeZone:"منطقتك الزمنية", change:"تغيير",
      yourLanguage:"اللغة", languageAuto:"تلقائي (الجهاز)", saveLanguage:"حفظ اللغة",
      inGameName:"الاسم داخل اللعبة", playerId:"Player ID", alliance:"التحالف", selectAlliance:"اختر التحالف",
      notListed:"غير مدرج", allianceTag:"Tag التحالف", addAccount:"إضافة حساب", saveChanges:"حفظ التغييرات",
      cancel:"إلغاء", edit:"تعديل", delete:"حذف", noAccounts:"لا توجد حسابات WOS مرتبطة بعد.",
      accountAdded:"تمت إضافة الحساب.", accountUpdated:"تم تحديث الحساب.", timezoneUpdated:"تم تحديث المنطقة الزمنية.",
      languageUpdated:"تم تحديث اللغة.", removeAccount:"إزالة حساب WOS هذا من NEXA؟",
      adminPanel:"لوحة الإدارة", controlCenter:"مركز تحكم NEXA", events:"الأحداث", alliances:"التحالفات",
      permissions:"الصلاحيات", svsEvents:"أحداث SvS",
      eventsHelp:"أنشئ وأدر SvS الحالي باستخدام توقيت WOS الرسمي (UTC).",
      opponentState:"State الخصم", prepMonday:"اثنين التحضير — تاريخ اللعبة (UTC)", eventNotes:"ملاحظات الحدث",
      timeline:"الجدول التلقائي لـ WOS", chooseMonday:"اختر اثنين التحضير لمعاينة التواريخ.",
      prepFormOpen:"Prep Form مفتوح", battleFormOpen:"Battle Form مفتوح",
      schedulePublished:"Schedule منشور", liveEvent:"حدث مباشر", saveEvent:"حفظ الحدث",
      noEvents:"لا توجد أحداث SvS بعد.", deleteEvent:"حذف حدث SvS هذا؟",
      allianceTags:"Tags التحالفات", allianceHelp:"أضف أو غيّر أو عطّل الـ tags الرسمية.",
      saveTag:"حفظ الـ Tag", active:"نشط", inactive:"غير نشط", deactivate:"تعطيل", activate:"تفعيل",
      permissionsHelp:"ابحث بالـ IGN أو Player ID وامنح الصلاحية. حساب Owner محمي.",
      searchUser:"ابحث IGN أو Player ID", search:"بحث", role:"الدور", player:"Player",
      scheduler:"Scheduler", owner:"Owner", noUsers:"لم يتم العثور على مستخدمين.",
      roleUpdated:"تم تحديث الدور.", ownerProtected:"حساب Owner محمي.",
      construction:"البناء", research:"البحث", training:"التدريب", battle:"معركة القلعة وPvP",
      fillPrep:"ملء Prep Form", fillBattle:"ملء Battle Form", viewSchedule:"عرض Schedule",
      aboutEvent:"عن هذا الحدث", noNotes:"لم تُنشر ملاحظات إضافية.",
      backEvents:"العودة للأحداث", backEvent:"العودة لحدث SvS", ministrySchedule:"Schedule الوزارات",
      officialUtc:"توقيت WOS الرسمي UTC • وقتك المحلي يظهر بصيغة AM/PM",
      appointments30:"مواعيد كل 30 دقيقة", yourTime:"وقتك", openUnassigned:"متاح / غير معيّن",
      publishedAppointments:"المواعيد المنشورة • State 1518", ended:"انتهى",
      monday:"الإثنين", tuesday:"الثلاثاء", thursday:"الخميس", saturday:"السبت"
    },
    ja: {
      "prepForm":"Prep Form",
      "wosAccount":"WOSアカウント",
      "requestVP":"VPを申請",
      "requestMOE":"MOEを申請",
      "constructionQuestion":"Construction Speedupを何分使う予定ですか？",
      "researchQuestion":"Research Speedupを何分使う予定ですか？",
      "trainingQuestion":"Training Speedupを何分使う予定ですか？",
      "minutesHint":"ゲームに表示される合計分数を入力してください。",
      "fireCrystalsQuestion":"Fire Crystalをいくつ使う予定ですか？",
      "refinedQuestion":"Refined Fire Crystalをいくつ使う予定ですか？",
      "shardsQuestion":"Fire Crystal Shardをいくつ使う予定ですか？",
      "timeFrame":"希望するUTC時間帯",
      "specificTime":"希望する特定UTC時刻（任意）",
      "troopsQuestion":"どの部隊を訓練/昇格しますか？",
      "upgradingT12":"T12へ昇格",
      "t12Info":"T12昇格情報",
      "submitPrep":"Prep Formを送信",
      "prepClosed":"現在Prep Formは閉じています。",
      "claimFirst":"Prep Form送信前にWOSアカウントを連携してください。",
      "prepSuccess":"Prep Formを送信しました。",
      "selectSomething":"少なくとも1つのPrep申請またはT12情報を選択してください。",
      "autoTranslate":"自動翻訳",
      "translationNote":"自由入力文の自動翻訳には翻訳サービスが必要です。下に手動翻訳を保存できます。",
      "editEvent":"イベント編集",
      "saveEventChanges":"変更を保存",
      "close":"閉じる",
      "castleAlliance":"城担当同盟",
      "presidencyAlliance":"大統領担当同盟",
      "eventNotes":"イベントメモ",
      "importantAnnouncement":"重要なお知らせ",
      "announcementHint":"NEXAホームに目立つメッセージとして表示されます。",
      "iveRead":"確認しました",
      "readConfirmed":"確認済み ✓",
      "announcementReads":"お知らせ確認状況",
      "optionalSchedulerNote":"Schedulerへの任意メモ",
      "mySubmissions":"自分の申請",
      "editSubmission":"申請を編集",
      "submitted":"送信済み",
      "reviewed":"確認済み",
      "partiallyScheduled":"一部割当済み",
      "scheduled":"割当済み",
      "copyAlliance":"同盟Scheduleをコピー",
      "copyDay":"この日をコピー",
      "copyFull":"全Scheduleをコピー",
      "exportCsv":"CSV出力",
      "allAlliances":"すべての同盟",
      "allDays":"すべての日",
      "prepRequests":"Prep申請",
      "scheduleTools":"Scheduleツール",
      admin:"管理", adminAccess:"管理者アクセスが必要です。", discordProfile:"Discordプロフィール",
      signInDiscord:"Discordでログイン", discordConnected:"Discord接続済み",
      myAccounts:"マイアカウント", claimAccount:"WOSアカウントを連携", open:"開く",
      accountSubtitle:"ゲーム名、Player ID、同盟を連携します。",
      liveUpcoming:"ライブ・今後のイベント", tapOpen:"タップして開く", live:"ライブ",
      viewEvent:"イベントを見る", noLive:"ライブSvSなし", noLiveText:"まだライブイベントは公開されていません。",
      endsIn:"終了まで", prepBattle:"準備・戦闘フェーズ", stateHub:"State 1518 • イベント・アカウント・調整",
      motto:"一つのState。一つのビジョン。一つの勝利。",
      wosAccounts:"WOSアカウント", yourTimeZone:"タイムゾーン", change:"変更",
      yourLanguage:"言語", languageAuto:"自動（端末）", saveLanguage:"言語を保存",
      inGameName:"ゲーム内名", playerId:"Player ID", alliance:"同盟", selectAlliance:"同盟を選択",
      notListed:"一覧にない", allianceTag:"同盟Tag", addAccount:"アカウント追加", saveChanges:"変更を保存",
      cancel:"キャンセル", edit:"編集", delete:"削除", noAccounts:"まだWOSアカウントがありません。",
      accountAdded:"アカウントを追加しました。", accountUpdated:"アカウントを更新しました。", timezoneUpdated:"タイムゾーンを更新しました。",
      languageUpdated:"言語を更新しました。", removeAccount:"このWOSアカウントをNEXAから削除しますか？",
      adminPanel:"管理パネル", controlCenter:"NEXAコントロールセンター", events:"イベント", alliances:"同盟",
      permissions:"権限", svsEvents:"SvSイベント",
      eventsHelp:"WOS公式ゲーム時間（UTC）で現在のSvSを管理します。",
      opponentState:"相手State", prepMonday:"準備月曜日 — ゲーム日付（UTC）", eventNotes:"イベントメモ",
      timeline:"自動WOSタイムライン", chooseMonday:"準備月曜日を選択して日付を確認します。",
      prepFormOpen:"Prep Form 開放", battleFormOpen:"Battle Form 開放",
      schedulePublished:"Schedule 公開", liveEvent:"ライブイベント", saveEvent:"イベント保存",
      noEvents:"SvSイベントはまだありません。", deleteEvent:"このSvSイベントを削除しますか？",
      allianceTags:"同盟Tags", allianceHelp:"公式Tagを追加・変更・無効化します。",
      saveTag:"Tag保存", active:"有効", inactive:"無効", deactivate:"無効化", activate:"有効化",
      permissionsHelp:"IGNまたはPlayer IDで検索して権限を設定します。Ownerは保護されます。",
      searchUser:"IGNまたはPlayer IDを検索", search:"検索", role:"役割", player:"Player",
      scheduler:"Scheduler", owner:"Owner", noUsers:"該当ユーザーなし。",
      roleUpdated:"役割を更新しました。", ownerProtected:"Ownerアカウントは保護されています。",
      construction:"建設", research:"研究", training:"訓練", battle:"城戦＆PvP",
      fillPrep:"Prep Form入力", fillBattle:"Battle Form入力", viewSchedule:"Scheduleを見る",
      aboutEvent:"イベントについて", noNotes:"追加メモはありません。",
      backEvents:"イベントに戻る", backEvent:"SvSイベントに戻る", ministrySchedule:"大臣Schedule",
      officialUtc:"WOS公式時間はUTC • 現地時間はAM/PMで表示",
      appointments30:"30分ごとの予約", yourTime:"あなたの時間", openUnassigned:"空き / 未割当",
      publishedAppointments:"公開済み予約 • State 1518", ended:"終了",
      monday:"月", tuesday:"火", thursday:"木", saturday:"土"
    },
    zh: {
      "prepForm":"Prep Form",
      "wosAccount":"WOS 账号",
      "requestVP":"申请 VP",
      "requestMOE":"申请 MOE",
      "constructionQuestion":"你计划使用多少分钟的 Construction Speedups？",
      "researchQuestion":"你计划使用多少分钟的 Research Speedups？",
      "trainingQuestion":"你计划使用多少分钟的 Training Speedups？",
      "minutesHint":"请输入游戏中显示的总分钟数。",
      "fireCrystalsQuestion":"你计划使用多少 Fire Crystals？",
      "refinedQuestion":"你计划使用多少 Refined Fire Crystals？",
      "shardsQuestion":"你计划使用多少 Fire Crystal Shards？",
      "timeFrame":"首选 UTC 时间段",
      "specificTime":"首选具体 UTC 时间（可选）",
      "troopsQuestion":"你要训练/晋升哪些部队？",
      "upgradingT12":"升级到 T12",
      "t12Info":"T12 升级信息",
      "submitPrep":"提交 Prep Form",
      "prepClosed":"当前 Prep Form 已关闭。",
      "claimFirst":"提交 Prep Form 前请先绑定 WOS 账号。",
      "prepSuccess":"Prep Form 已成功提交。",
      "selectSomething":"请至少选择一个 Prep 请求或 T12 信息。",
      "autoTranslate":"自动翻译",
      "translationNote":"自由文本自动翻译需要翻译服务。你可以在下方手动保存翻译。",
      "editEvent":"编辑活动",
      "saveEventChanges":"保存更改",
      "close":"关闭",
      "castleAlliance":"城堡联盟",
      "presidencyAlliance":"总统联盟",
      "eventNotes":"活动备注",
      "importantAnnouncement":"重要公告",
      "announcementHint":"将在 NEXA 首页以醒目消息显示。",
      "iveRead":"我已阅读",
      "readConfirmed":"已阅读 ✓",
      "announcementReads":"公告阅读记录",
      "optionalSchedulerNote":"给 Scheduler 的可选备注",
      "mySubmissions":"我的申请",
      "editSubmission":"编辑申请",
      "submitted":"已提交",
      "reviewed":"已审核",
      "partiallyScheduled":"部分已安排",
      "scheduled":"已安排",
      "copyAlliance":"复制联盟 Schedule",
      "copyDay":"复制当天",
      "copyFull":"复制完整 Schedule",
      "exportCsv":"导出 CSV",
      "allAlliances":"所有联盟",
      "allDays":"所有日期",
      "prepRequests":"Prep 申请",
      "scheduleTools":"Schedule 工具",
      admin:"管理", adminAccess:"需要管理员权限。", discordProfile:"Discord 资料",
      signInDiscord:"使用 Discord 登录", discordConnected:"Discord 已连接",
      myAccounts:"我的账号", claimAccount:"绑定 WOS 账号", open:"打开",
      accountSubtitle:"绑定游戏名、Player ID 和联盟。",
      liveUpcoming:"进行中和即将开始的活动", tapOpen:"点击打开", live:"进行中",
      viewEvent:"查看活动", noLive:"暂无进行中的 SvS", noLiveText:"管理团队尚未发布进行中的活动。",
      endsIn:"剩余", prepBattle:"准备与战斗阶段", stateHub:"State 1518 • 活动、账号与协调",
      motto:"同一个 State。同一个目标。同一场胜利。",
      wosAccounts:"WOS 账号", yourTimeZone:"你的时区", change:"更改",
      yourLanguage:"语言", languageAuto:"自动（设备）", saveLanguage:"保存语言",
      inGameName:"游戏内名称", playerId:"Player ID", alliance:"联盟", selectAlliance:"选择联盟",
      notListed:"不在列表", allianceTag:"联盟 Tag", addAccount:"添加账号", saveChanges:"保存更改",
      cancel:"取消", edit:"编辑", delete:"删除", noAccounts:"尚未绑定 WOS 账号。",
      accountAdded:"账号已添加。", accountUpdated:"账号已更新。", timezoneUpdated:"时区已更新。",
      languageUpdated:"语言已更新。", removeAccount:"从 NEXA 移除此 WOS 账号？",
      adminPanel:"管理面板", controlCenter:"NEXA 控制中心", events:"活动", alliances:"联盟",
      permissions:"权限", svsEvents:"SvS 活动",
      eventsHelp:"使用 WOS 官方游戏时间（UTC）创建和管理当前 SvS。",
      opponentState:"对手 State", prepMonday:"准备周一 — 游戏日期（UTC）", eventNotes:"活动备注",
      timeline:"自动 WOS 时间表", chooseMonday:"选择准备周一以预览日期。",
      prepFormOpen:"Prep Form 开放", battleFormOpen:"Battle Form 开放",
      schedulePublished:"Schedule 已发布", liveEvent:"进行中活动", saveEvent:"保存活动",
      noEvents:"尚未创建 SvS 活动。", deleteEvent:"删除此 SvS 活动？",
      allianceTags:"联盟 Tags", allianceHelp:"添加、修改或停用官方 Tags。",
      saveTag:"保存 Tag", active:"启用", inactive:"停用", deactivate:"停用", activate:"启用",
      permissionsHelp:"通过 IGN 或 Player ID 搜索并分配权限。Owner 受保护。",
      searchUser:"搜索 IGN 或 Player ID", search:"搜索", role:"角色", player:"Player",
      scheduler:"Scheduler", owner:"Owner", noUsers:"未找到匹配用户。",
      roleUpdated:"角色已更新。", ownerProtected:"Owner 账号受保护。",
      construction:"建造", research:"研究", training:"训练", battle:"城堡战与 PvP",
      fillPrep:"填写 Prep Form", fillBattle:"填写 Battle Form", viewSchedule:"查看 Schedule",
      aboutEvent:"关于此活动", noNotes:"暂无额外备注。",
      backEvents:"返回活动", backEvent:"返回 SvS 活动", ministrySchedule:"部长 Schedule",
      officialUtc:"WOS 官方时间为 UTC • 本地时间以 AM/PM 显示",
      appointments30:"每 30 分钟一个预约", yourTime:"你的时间", openUnassigned:"空闲 / 未分配",
      publishedAppointments:"已发布预约 • State 1518", ended:"已结束",
      monday:"周一", tuesday:"周二", thursday:"周四", saturday:"周六"
    },
    ru: {
      "prepForm":"Prep Form",
      "wosAccount":"Аккаунт WOS",
      "requestVP":"Запросить VP",
      "requestMOE":"Запросить MOE",
      "constructionQuestion":"Сколько минут Construction Speedups вы планируете использовать?",
      "researchQuestion":"Сколько минут Research Speedups вы планируете использовать?",
      "trainingQuestion":"Сколько минут Training Speedups вы планируете использовать?",
      "minutesHint":"Введите общее количество минут, показанное в игре.",
      "fireCrystalsQuestion":"Сколько Fire Crystals вы планируете использовать?",
      "refinedQuestion":"Сколько Refined Fire Crystals вы планируете использовать?",
      "shardsQuestion":"Сколько Fire Crystal Shards вы планируете использовать?",
      "timeFrame":"Предпочтительный интервал UTC",
      "specificTime":"Предпочтительное точное время UTC (необязательно)",
      "troopsQuestion":"Какие войска вы тренируете/повышаете?",
      "upgradingT12":"Повышение до T12",
      "t12Info":"Информация о повышении T12",
      "submitPrep":"Отправить Prep Form",
      "prepClosed":"Prep Form сейчас закрыт.",
      "claimFirst":"Привяжите аккаунт WOS перед отправкой Prep Form.",
      "prepSuccess":"Prep Form успешно отправлен.",
      "selectSomething":"Выберите хотя бы один Prep-запрос или информацию T12.",
      "autoTranslate":"Автоперевод",
      "translationNote":"Для автоматического перевода свободного текста нужен сервис перевода. Ниже можно сохранить переводы вручную.",
      "editEvent":"Редактировать событие",
      "saveEventChanges":"Сохранить изменения",
      "close":"Закрыть",
      "castleAlliance":"Альянс замка",
      "presidencyAlliance":"Альянс президентства",
      "eventNotes":"Заметки события",
      "importantAnnouncement":"Важное объявление",
      "announcementHint":"Будет показано как заметное сообщение на главной странице NEXA.",
      "iveRead":"Я прочитал(а)",
      "readConfirmed":"Прочитано ✓",
      "announcementReads":"Кто прочитал",
      "optionalSchedulerNote":"Необязательная заметка для Scheduler",
      "mySubmissions":"Мои заявки",
      "editSubmission":"Изменить заявку",
      "submitted":"Отправлено",
      "reviewed":"Проверено",
      "partiallyScheduled":"Частично назначено",
      "scheduled":"Назначено",
      "copyAlliance":"Копировать Schedule альянса",
      "copyDay":"Копировать этот день",
      "copyFull":"Копировать полный Schedule",
      "exportCsv":"Экспорт CSV",
      "allAlliances":"Все альянсы",
      "allDays":"Все дни",
      "prepRequests":"Prep заявки",
      "scheduleTools":"Инструменты Schedule",
      admin:"Админ", adminAccess:"Требуется доступ администратора.", discordProfile:"Профиль Discord",
      signInDiscord:"Войти через Discord", discordConnected:"Discord подключен",
      myAccounts:"Мои аккаунты", claimAccount:"Привязать аккаунт WOS", open:"Открыть",
      accountSubtitle:"Привяжите игровой ник, Player ID и альянс.",
      liveUpcoming:"Текущие и предстоящие события", tapOpen:"Нажмите, чтобы открыть", live:"LIVE",
      viewEvent:"Открыть событие", noLive:"Нет активного SvS", noLiveText:"Руководство ещё не опубликовало активное событие.",
      endsIn:"До конца", prepBattle:"Подготовка и бой", stateHub:"State 1518 • События, аккаунты и координация",
      motto:"Один State. Одна цель. Одна победа.",
      wosAccounts:"Аккаунты WOS", yourTimeZone:"Ваш часовой пояс", change:"Изменить",
      yourLanguage:"Язык", languageAuto:"Авто (устройство)", saveLanguage:"Сохранить язык",
      inGameName:"Игровое имя", playerId:"Player ID", alliance:"Альянс", selectAlliance:"Выберите альянс",
      notListed:"Нет в списке", allianceTag:"Tag альянса", addAccount:"Добавить аккаунт", saveChanges:"Сохранить",
      cancel:"Отмена", edit:"Изменить", delete:"Удалить", noAccounts:"Аккаунты WOS ещё не привязаны.",
      accountAdded:"Аккаунт добавлен.", accountUpdated:"Аккаунт обновлён.", timezoneUpdated:"Часовой пояс обновлён.",
      languageUpdated:"Язык обновлён.", removeAccount:"Удалить этот аккаунт WOS из NEXA?",
      adminPanel:"ПАНЕЛЬ АДМИНА", controlCenter:"Центр управления NEXA", events:"События", alliances:"Альянсы",
      permissions:"Права", svsEvents:"События SvS",
      eventsHelp:"Создавайте и управляйте текущим SvS по официальному времени WOS (UTC).",
      opponentState:"State противника", prepMonday:"Понедельник Prep — дата игры (UTC)", eventNotes:"Заметки события",
      timeline:"АВТОМАТИЧЕСКОЕ РАСПИСАНИЕ WOS", chooseMonday:"Выберите понедельник Prep для просмотра дат.",
      prepFormOpen:"Prep Form открыт", battleFormOpen:"Battle Form открыт",
      schedulePublished:"Schedule опубликован", liveEvent:"Активное событие", saveEvent:"Сохранить событие",
      noEvents:"События SvS ещё не созданы.", deleteEvent:"Удалить это событие SvS?",
      allianceTags:"Tags альянсов", allianceHelp:"Добавляйте, меняйте или отключайте официальные tags.",
      saveTag:"Сохранить tag", active:"Активен", inactive:"Неактивен", deactivate:"Отключить", activate:"Включить",
      permissionsHelp:"Ищите по IGN или Player ID и назначайте доступ. Owner защищён.",
      searchUser:"Поиск IGN или Player ID", search:"Поиск", role:"Роль", player:"Player",
      scheduler:"Scheduler", owner:"Owner", noUsers:"Пользователи не найдены.",
      roleUpdated:"Роль обновлена.", ownerProtected:"Аккаунт Owner защищён.",
      construction:"Строительство", research:"Исследования", training:"Тренировка", battle:"Битва за замок и PvP",
      fillPrep:"Заполнить Prep Form", fillBattle:"Заполнить Battle Form", viewSchedule:"Открыть Schedule",
      aboutEvent:"О событии", noNotes:"Дополнительных заметок нет.",
      backEvents:"Назад к событиям", backEvent:"Назад к SvS", ministrySchedule:"Schedule министерств",
      officialUtc:"Официальное время WOS — UTC • местное время показывается в AM/PM",
      appointments30:"Запись каждые 30 минут", yourTime:"Ваше время", openUnassigned:"Свободно / Не назначено",
      publishedAppointments:"Опубликованные записи • State 1518", ended:"Завершено",
      monday:"ПН", tuesday:"ВТ", thursday:"ЧТ", saturday:"СБ"
    }
  };

  const supported = ["en","es","tr","ko","ar","ja","zh","ru"];
  function normalize(v){
    if(!v || v==="auto") return null;
    const s=String(v).toLowerCase();
    if(s.startsWith("zh")) return "zh";
    const p=s.split("-")[0];
    return supported.includes(p)?p:null;
  }
  function device(){
    return normalize(navigator.language) || normalize((navigator.languages||[])[0]) || "en";
  }
  function resolve(pref){ return normalize(pref) || device(); }
  function t(lang,key){ return (D[lang]&&D[lang][key]) || D.en[key] || key; }
  function setDir(lang){
    document.documentElement.lang=lang;
    document.documentElement.dir=lang==="ar"?"rtl":"ltr";
    document.body.classList.toggle("rtl",lang==="ar");
  }
  window.NEXA_I18N={D,supported,normalize,device,resolve,t,setDir};
})();
