-- NEXA Administration — Alliance Passports V1
-- Run once in Supabase SQL Editor.

begin;

alter table public.alliances
  add column if not exists color text,
  add column if not exists emblem_url text,
  add column if not exists server_rank integer,
  add column if not exists game_power bigint,
  add column if not exists deletion_requested_at timestamptz,
  add column if not exists deletion_requested_by uuid,
  add column if not exists scheduled_delete_at timestamptz,
  add column if not exists deletion_status text not null default 'active';

alter table public.alliances drop constraint if exists alliances_deletion_status_check;
alter table public.alliances add constraint alliances_deletion_status_check
  check (deletion_status in ('active','pending_deletion'));

create table if not exists public.player_operational_roles (
  player_account_id uuid not null references public.player_accounts(id) on delete cascade,
  role_key text not null check (role_key in ('scheduler','svs','transfers','event_operations','team_builder','test_lab')),
  granted_by uuid not null default auth.uid(),
  granted_at timestamptz not null default now(),
  primary key (player_account_id, role_key)
);

create table if not exists public.nexa_admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  action_key text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.player_operational_roles enable row level security;
alter table public.nexa_admin_audit_log enable row level security;
revoke all on public.player_operational_roles from anon, authenticated;
revoke all on public.nexa_admin_audit_log from anon, authenticated;

create or replace function public.nexa_is_owner()
returns boolean language sql stable security invoker set search_path=''
as $$
  select coalesce((select ur.role='owner' from public.user_roles ur where ur.user_id=(select auth.uid())),false)
$$;

create or replace function public.nexa_is_admin()
returns boolean language sql stable security invoker set search_path=''
as $$
  select coalesce((select ur.role in ('owner','admin') from public.user_roles ur where ur.user_id=(select auth.uid())),false)
$$;

create or replace function public.nexa_alliance_rank(p_alliance_id bigint)
returns text language sql stable security invoker set search_path=''
as $$
  select pa.alliance_role
  from public.player_accounts pa
  where pa.user_id=(select auth.uid()) and pa.alliance_id=p_alliance_id
  order by case pa.alliance_role when 'R5' then 5 when 'R4' then 4 when 'R3' then 3 when 'R2' then 2 else 1 end desc
  limit 1
$$;

create or replace function public.nexa_can_view_alliance_admin(p_alliance_id bigint)
returns boolean language sql stable security invoker set search_path=''
as $$ select public.nexa_is_admin() or public.nexa_alliance_rank(p_alliance_id) in ('R5','R4') $$;

create or replace function public.nexa_can_manage_alliance(p_alliance_id bigint)
returns boolean language sql stable security invoker set search_path=''
as $$ select public.nexa_is_admin() or public.nexa_alliance_rank(p_alliance_id)='R5' $$;

create or replace function public.nexa_has_alliance_staff_access()
returns boolean language sql stable security invoker set search_path=''
as $$
  select public.nexa_is_admin() or exists(
    select 1 from public.player_accounts pa
    where pa.user_id=(select auth.uid()) and pa.alliance_role in ('R5','R4')
  )
$$;

create or replace function public.nexa_finalize_due_alliance_deletions()
returns integer language plpgsql security definer set search_path=''
as $$
declare v_count integer:=0; v_row record;
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  for v_row in
    select a.id,a.tag from public.alliances a
    where a.deletion_status='pending_deletion' and a.scheduled_delete_at<=now()
  loop
    update public.player_accounts set alliance_id=null,custom_alliance_tag=null,alliance_role=null,updated_at=now()
      where alliance_id=v_row.id;
    update public.guest_prep_requests set alliance_id=null where alliance_id=v_row.id;
    update public.svs_events set castle_alliance_id=null where castle_alliance_id=v_row.id;
    update public.svs_events set presidency_alliance_id=null where presidency_alliance_id=v_row.id;
    delete from public.alliances where id=v_row.id;
    insert into public.nexa_admin_audit_log(actor_user_id,action_key,target_type,target_id,details)
      values(null,'alliance_deleted_after_cooldown','alliance',v_row.id::text,jsonb_build_object('tag',v_row.tag));
    v_count:=v_count+1;
  end loop;
  return v_count;
end
$$;

create or replace function public.nexa_list_alliance_passports()
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_result jsonb;
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  perform public.nexa_finalize_due_alliance_deletions();
  select coalesce(jsonb_agg(x.obj order by x.sort_active desc,x.tag),'[]'::jsonb) into v_result
  from (
    select a.tag, a.is_active as sort_active,
      jsonb_build_object(
        'id',a.id,'tag',a.tag,'name',coalesce(a.name,a.tag),'active',a.is_active,
        'color',coalesce(a.color,case (a.id%6) when 0 then '#8b5cf6' when 1 then '#22d3ee' when 2 then '#ec4899' when 3 then '#3b82f6' when 4 then '#34d399' else '#f59e0b' end),
        'emblemUrl',a.emblem_url,'serverRank',a.server_rank,'gamePower',a.game_power,
        'registeredPower',coalesce(sum(pa.power),0),'registeredMembers',count(pa.id),
        'deletionStatus',a.deletion_status,'scheduledDeleteAt',a.scheduled_delete_at,
        'canManage',public.nexa_can_manage_alliance(a.id),
        'canAssignRanks',public.nexa_can_view_alliance_admin(a.id),
        'members',case when public.nexa_can_view_alliance_admin(a.id) then coalesce(jsonb_agg(jsonb_build_object(
          'accountId',pa.id,'userId',pa.user_id,'gameId',pa.player_id,'name',pa.in_game_name,
          'rank',coalesce(pa.alliance_role,'R3'),'power',pa.power,'photo',pa.profile_photo_url,
          'isMain',pa.is_main,
          'roles',coalesce((select jsonb_agg(por.role_key order by por.role_key) from public.player_operational_roles por where por.player_account_id=pa.id),'[]'::jsonb)
        ) order by case pa.alliance_role when 'R5' then 5 when 'R4' then 4 when 'R3' then 3 when 'R2' then 2 else 1 end desc,pa.in_game_name)
          filter(where pa.id is not null),'[]'::jsonb) else '[]'::jsonb end
      ) obj
    from public.alliances a left join public.player_accounts pa on pa.alliance_id=a.id
    group by a.id
  ) x;
  return v_result;
end
$$;

create or replace function public.nexa_list_unassigned_passport()
returns jsonb language sql security definer set search_path=''
as $$
  select case when public.nexa_is_admin() then jsonb_build_object(
    'id',null,'tag','UNASSIGNED','name','Unassigned','active',true,'color','#64748b',
    'registeredPower',coalesce(sum(pa.power),0),'registeredMembers',count(pa.id),
    'members',coalesce(jsonb_agg(jsonb_build_object(
      'accountId',pa.id,'userId',pa.user_id,'gameId',pa.player_id,'name',pa.in_game_name,
      'rank',null,'power',pa.power,'photo',pa.profile_photo_url,'isMain',pa.is_main,
      'roles',coalesce((select jsonb_agg(por.role_key order by por.role_key) from public.player_operational_roles por where por.player_account_id=pa.id),'[]'::jsonb)
    ) order by pa.in_game_name) filter(where pa.id is not null),'[]'::jsonb)
  ) else jsonb_build_object('id',null,'tag','UNASSIGNED','name','Unassigned','active',true,'color','#64748b','registeredPower',0,'registeredMembers',0,'members','[]'::jsonb) end
  from public.player_accounts pa where pa.alliance_id is null
$$;

create or replace function public.nexa_update_alliance_passport(
  p_alliance_id bigint,p_name text,p_color text,p_server_rank integer,p_game_power bigint,p_is_active boolean
) returns void language plpgsql security definer set search_path=''
as $$
begin
  if not public.nexa_can_manage_alliance(p_alliance_id) then raise exception 'Not authorized'; end if;
  update public.alliances set name=nullif(trim(p_name),''),color=p_color,server_rank=p_server_rank,game_power=p_game_power,is_active=p_is_active
  where id=p_alliance_id;
  insert into public.nexa_admin_audit_log(actor_user_id,action_key,target_type,target_id,details)
  values((select auth.uid()),'alliance_updated','alliance',p_alliance_id::text,jsonb_build_object('name',p_name,'active',p_is_active));
end
$$;

create or replace function public.nexa_request_alliance_deletion(p_alliance_id bigint)
returns timestamptz language plpgsql security definer set search_path=''
as $$
declare v_when timestamptz:=now()+interval '24 hours';
begin
  if not public.nexa_can_manage_alliance(p_alliance_id) then raise exception 'Only Owner, Admin or this alliance''s R5 can delete it'; end if;
  update public.alliances set deletion_status='pending_deletion',deletion_requested_at=now(),deletion_requested_by=(select auth.uid()),scheduled_delete_at=v_when,is_active=false
  where id=p_alliance_id;
  if not found then raise exception 'Alliance not found'; end if;
  insert into public.nexa_admin_audit_log(actor_user_id,action_key,target_type,target_id,details)
  values((select auth.uid()),'alliance_deletion_requested','alliance',p_alliance_id::text,jsonb_build_object('scheduledAt',v_when));
  return v_when;
end
$$;

create or replace function public.nexa_cancel_alliance_deletion(p_alliance_id bigint)
returns void language plpgsql security definer set search_path=''
as $$
begin
  if not public.nexa_can_manage_alliance(p_alliance_id) then raise exception 'Not authorized'; end if;
  update public.alliances set deletion_status='active',deletion_requested_at=null,deletion_requested_by=null,scheduled_delete_at=null,is_active=true
  where id=p_alliance_id and deletion_status='pending_deletion';
  insert into public.nexa_admin_audit_log(actor_user_id,action_key,target_type,target_id)
  values((select auth.uid()),'alliance_deletion_cancelled','alliance',p_alliance_id::text);
end
$$;

create or replace function public.nexa_set_alliance_rank(p_account_id uuid,p_new_rank text)
returns void language plpgsql security definer set search_path=''
as $$
declare v_alliance bigint; v_my_rank text; v_target_rank text;
begin
  if p_new_rank not in ('R1','R2','R3','R4','R5') then raise exception 'Invalid rank'; end if;
  select alliance_id,alliance_role into v_alliance,v_target_rank from public.player_accounts where id=p_account_id;
  if v_alliance is null then raise exception 'Player is Unassigned'; end if;
  if public.nexa_is_admin() then null;
  else
    v_my_rank:=public.nexa_alliance_rank(v_alliance);
    if v_my_rank='R5' and p_new_rank not in ('R1','R2','R3','R4') then raise exception 'R5 can assign R4-R1 only'; end if;
    if v_my_rank='R4' and p_new_rank not in ('R1','R2','R3') then raise exception 'R4 can assign R3-R1 only'; end if;
    if v_my_rank not in ('R5','R4') then raise exception 'Not authorized'; end if;
  end if;
  if exists(select 1 from public.player_accounts where id=p_account_id and user_id=(select auth.uid())) then raise exception 'You cannot change your own rank'; end if;
  update public.player_accounts set alliance_role=p_new_rank,updated_at=now() where id=p_account_id;
  insert into public.nexa_admin_audit_log(actor_user_id,action_key,target_type,target_id,details)
  values((select auth.uid()),'alliance_rank_changed','player_account',p_account_id::text,jsonb_build_object('from',v_target_rank,'to',p_new_rank));
end
$$;

create or replace function public.nexa_set_operational_roles(p_account_id uuid,p_roles text[])
returns void language plpgsql security definer set search_path=''
as $$
declare v_alliance bigint;
begin
  select alliance_id into v_alliance from public.player_accounts where id=p_account_id;
  if v_alliance is null or not public.nexa_can_view_alliance_admin(v_alliance) then raise exception 'Not authorized'; end if;
  if exists(select 1 from unnest(coalesce(p_roles,array[]::text[])) r where r not in ('scheduler','svs','transfers','event_operations','team_builder','test_lab')) then raise exception 'Invalid role'; end if;
  if 'test_lab'=any(coalesce(p_roles,array[]::text[])) and not public.nexa_is_admin() then raise exception 'Only Owner or Admin can grant Test Lab'; end if;
  delete from public.player_operational_roles where player_account_id=p_account_id;
  insert into public.player_operational_roles(player_account_id,role_key,granted_by)
    select p_account_id,r,(select auth.uid()) from unnest(coalesce(p_roles,array[]::text[])) r;
  insert into public.nexa_admin_audit_log(actor_user_id,action_key,target_type,target_id,details)
  values((select auth.uid()),'operational_roles_changed','player_account',p_account_id::text,jsonb_build_object('roles',p_roles));
end
$$;

create or replace function public.nexa_find_admin_candidate(p_game_id text)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_result jsonb;
begin
  if not public.nexa_is_owner() then raise exception 'Owner only'; end if;
  select jsonb_build_object('userId',pa.user_id,'accountId',pa.id,'gameId',pa.player_id,'name',pa.in_game_name,
    'alliance',coalesce(a.tag,'Unassigned'),'rank',pa.alliance_role,
    'nexaRole',coalesce(ur.role,'player')) into v_result
  from public.player_accounts pa left join public.alliances a on a.id=pa.alliance_id
  left join public.user_roles ur on ur.user_id=pa.user_id
  where regexp_replace(pa.player_id,'[^0-9A-Za-z]','','g')=regexp_replace(p_game_id,'[^0-9A-Za-z]','','g') limit 1;
  return v_result;
end
$$;

create or replace function public.nexa_assign_admin_by_game_id(p_game_id text)
returns void language plpgsql security definer set search_path=''
as $$
declare v_user uuid;
begin
  if not public.nexa_is_owner() then raise exception 'Owner only'; end if;
  select user_id into v_user from public.player_accounts where regexp_replace(player_id,'[^0-9A-Za-z]','','g')=regexp_replace(p_game_id,'[^0-9A-Za-z]','','g') limit 1;
  if v_user is null then raise exception 'Game ID not found'; end if;
  insert into public.user_roles(user_id,role) values(v_user,'admin') on conflict(user_id) do update set role='admin',updated_at=now();
  insert into public.nexa_admin_audit_log(actor_user_id,action_key,target_type,target_id)
  values((select auth.uid()),'admin_assigned','user',v_user::text);
end
$$;

create or replace function public.nexa_remove_admin(p_user_id uuid)
returns void language plpgsql security definer set search_path=''
as $$
begin
  if not public.nexa_is_owner() then raise exception 'Owner only'; end if;
  if exists(select 1 from public.user_roles where user_id=p_user_id and role='owner') then raise exception 'Owner is protected'; end if;
  update public.user_roles set role='player',updated_at=now() where user_id=p_user_id and role='admin';
  insert into public.nexa_admin_audit_log(actor_user_id,action_key,target_type,target_id)
  values((select auth.uid()),'admin_removed','user',p_user_id::text);
end
$$;

create or replace function public.nexa_list_admins()
returns jsonb language sql security definer set search_path=''
as $$
 select case when public.nexa_is_owner() then coalesce(jsonb_agg(jsonb_build_object(
   'userId',ur.user_id,'role',ur.role,'name',pa.in_game_name,'gameId',pa.player_id,'alliance',coalesce(a.tag,'Unassigned')
 ) order by case ur.role when 'owner' then 0 else 1 end,pa.in_game_name),'[]'::jsonb) else '[]'::jsonb end
 from public.user_roles ur
 left join lateral (select * from public.player_accounts p where p.user_id=ur.user_id order by p.is_main desc,p.created_at limit 1) pa on true
 left join public.alliances a on a.id=pa.alliance_id where ur.role in ('owner','admin')
$$;

revoke execute on function public.nexa_finalize_due_alliance_deletions() from public,anon;
revoke execute on function public.nexa_is_owner() from public,anon;
revoke execute on function public.nexa_is_admin() from public,anon;
revoke execute on function public.nexa_alliance_rank(bigint) from public,anon;
revoke execute on function public.nexa_can_view_alliance_admin(bigint) from public,anon;
revoke execute on function public.nexa_can_manage_alliance(bigint) from public,anon;
revoke execute on function public.nexa_has_alliance_staff_access() from public,anon;
revoke execute on function public.nexa_list_alliance_passports() from public,anon;
revoke execute on function public.nexa_list_unassigned_passport() from public,anon;
revoke execute on function public.nexa_update_alliance_passport(bigint,text,text,integer,bigint,boolean) from public,anon;
revoke execute on function public.nexa_request_alliance_deletion(bigint) from public,anon;
revoke execute on function public.nexa_cancel_alliance_deletion(bigint) from public,anon;
revoke execute on function public.nexa_set_alliance_rank(uuid,text) from public,anon;
revoke execute on function public.nexa_set_operational_roles(uuid,text[]) from public,anon;
revoke execute on function public.nexa_find_admin_candidate(text) from public,anon;
revoke execute on function public.nexa_assign_admin_by_game_id(text) from public,anon;
revoke execute on function public.nexa_remove_admin(uuid) from public,anon;
revoke execute on function public.nexa_list_admins() from public,anon;

grant execute on function public.nexa_finalize_due_alliance_deletions() to authenticated;
grant execute on function public.nexa_is_owner() to authenticated;
grant execute on function public.nexa_is_admin() to authenticated;
grant execute on function public.nexa_alliance_rank(bigint) to authenticated;
grant execute on function public.nexa_can_view_alliance_admin(bigint) to authenticated;
grant execute on function public.nexa_can_manage_alliance(bigint) to authenticated;
grant execute on function public.nexa_has_alliance_staff_access() to authenticated;
grant execute on function public.nexa_list_alliance_passports() to authenticated;
grant execute on function public.nexa_list_unassigned_passport() to authenticated;
grant execute on function public.nexa_update_alliance_passport(bigint,text,text,integer,bigint,boolean) to authenticated;
grant execute on function public.nexa_request_alliance_deletion(bigint) to authenticated;
grant execute on function public.nexa_cancel_alliance_deletion(bigint) to authenticated;
grant execute on function public.nexa_set_alliance_rank(uuid,text) to authenticated;
grant execute on function public.nexa_set_operational_roles(uuid,text[]) to authenticated;
grant execute on function public.nexa_find_admin_candidate(text) to authenticated;
grant execute on function public.nexa_assign_admin_by_game_id(text) to authenticated;
grant execute on function public.nexa_remove_admin(uuid) to authenticated;
grant execute on function public.nexa_list_admins() to authenticated;

commit;
