-- NEXA Phase 2A • Event Operations + Dynamic Question Library
-- Run once in Supabase SQL Editor before using Event Operations.

create table if not exists public.event_form_questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  event_scopes text[] not null default array['svs']::text[],
  role_scope text not null default 'both' check (role_scope in ('joiner','rally_lead','both','everyone')),
  answer_type text not null default 'short_text' check (answer_type in ('short_text','long_text','number','dropdown','single_choice','multiple_choice','checkboxes')),
  options jsonb not null default '[]'::jsonb,
  is_required boolean not null default false,
  is_permanent boolean not null default true,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.event_form_layouts (
  id bigint generated by default as identity primary key,
  event_scope text not null check (event_scope in ('svs','tal','fdt')),
  role_scope text not null check (role_scope in ('joiner','rally_lead')),
  field_order jsonb not null default '[]'::jsonb,
  updated_by uuid default auth.uid(),
  updated_at timestamptz not null default now(),
  unique(event_scope, role_scope)
);

alter table public.event_form_questions enable row level security;
alter table public.event_form_layouts enable row level security;

drop policy if exists "event form questions authenticated read" on public.event_form_questions;
create policy "event form questions authenticated read" on public.event_form_questions
for select to authenticated using (true);

drop policy if exists "event form questions staff write" on public.event_form_questions;
create policy "event form questions staff write" on public.event_form_questions
for all to authenticated
using (public.current_nexa_role() in ('owner','admin','scheduler'))
with check (public.current_nexa_role() in ('owner','admin','scheduler'));

drop policy if exists "event form layouts authenticated read" on public.event_form_layouts;
create policy "event form layouts authenticated read" on public.event_form_layouts
for select to authenticated using (true);

drop policy if exists "event form layouts staff write" on public.event_form_layouts;
create policy "event form layouts staff write" on public.event_form_layouts
for all to authenticated
using (public.current_nexa_role() in ('owner','admin','scheduler'))
with check (public.current_nexa_role() in ('owner','admin','scheduler'));

alter table public.battle_form_responses
  add column if not exists custom_answers jsonb not null default '{}'::jsonb;

grant select, insert, update, delete on public.event_form_questions to authenticated;
grant select, insert, update, delete on public.event_form_layouts to authenticated;
grant usage, select on all sequences in schema public to authenticated;
